### PR TITLE
Make print python3-compatible

### PR DESCRIPTION
**Pull request by vargasa**
There are some other changes that need to be done in order to make it fully `p3` compatible (as seen from AIEH):

`/cmstoolbox/webtools.py` :

 * remove `__func__`

`/cmstoolbox/dashboard.py` :

 * change `httplib` to `http.client`

But I think as of now they can't be included without breaking `p2`, therefore those changes are not included here

### CODE REVIEW

**Comment by dabercro** [comment]
I think adding `from __future__ import print_function` should fix the pylint errors. We should also add the desired Python version to the matrix here: https://github.com/CMSCompOps/OpsSpace/blob/master/.travis.yml

**Comment by vargasa** [comment]
@dabercro Is it because `python2.6` is listed?

**Comment by dabercro** [comment]
The pylint complaint happens for Python 2.7 too.

I'm sure something else will pop up too once we add Python 3.x to the list of versions tested.

**Comment by vargasa** [comment]
@dabercro I have made a couple of tests on this PR, so the errors that we originally saw are not coming from the PR itself

**Comment by dabercro** [comment]
Remind me about this tomorrow. I think the current errors should be easy to fix, but we should also have the tests themselves run in Python 3. I expect a few more old code smells will pop up then.

**Pull request closed without merging**
